#change the distro if needed, you can also use a ubuntu image and make your custom ROS install on it.
FROM ros:foxy
ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update

# ROS related dependency
RUN apt-get install -y build-essential sudo terminator iproute2 gedit lsb-release lsb-core wget nano ros-foxy-rviz

# Debug related dependency (removed when official package is ready)
RUN apt-get install -y iputils-ping

RUN adduser user
RUN adduser user sudo
#remove password
RUN passwd -d user

USER user